using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using SuplementosWPF.DAO;
using SuplementosWPF.Model;

namespace SuplementosWPF.View
{
    /// <summary>
    /// Interaction logic for frmCadastrarVenda.xaml
    /// </summary>
    public partial class frmCadastrarVenda : Window
    {

        public frmCadastrarVenda()
        {
            InitializeComponent();
        }

        List<dynamic> listaDeItens = new List<dynamic>();

        private void btnAdicionar_Click(object sender, RoutedEventArgs e)
        {
            int idProduto = (int)cboSuplementos.SelectedValue;
            Suplemento suplemento = SuplementoDAO.BuscarSuplementoPorId(idProduto);
            double precoUnitario = suplemento.Markup * suplemento.Preco;
            double subtotal = precoUnitario * Convert.ToInt32(txtQuantidade.Text);

            listaDeItens.Add(new
            {
                NomeSuplemento = suplemento.Nome,
                Quantidade = txtQuantidade.Text,
                Unitario = precoUnitario.ToString("C2"),
                Subtotal = subtotal.ToString("C2")
            });
            dtaSuplementos.ItemsSource = listaDeItens;
            dtaSuplementos.Items.Refresh();
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            //carregar dados no combobox
            cboSuplementos.ItemsSource = SuplementoDAO.RetornarLista();
            cboSuplementos.DisplayMemberPath = "Nome";
            cboSuplementos.SelectedValuePath = "ProdutoId";

            //carregar dados na grid
            dtaSuplementos.ItemsSource = SuplementoDAO.RetornarLista();
        }

        private void dtaSuplementos_AutoGeneratedColumns(object sender, EventArgs e)
        {

        }

        private void cboSuplementos_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {

        }
    }
}
